---
swagger: "2.0"
info:
  description: "Sandboxed Weasyprint, only use external files provided within the\
    \ call"
  version: "0.0.1"
  title: "Sandboxed Weasyprint"
  termsOfService: "https://localhost"
  contact:
    email: "jowenn@jowenn.net"
  license:
    name: "MIT"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "sandboxed_weasyprint"
basePath: "/v1"
tags:
- name: "html2pdf"
  description: "Converts html to pdf"
  externalDocs:
    description: "Find out more"
    url: "https://www.jowenn.net"
schemes:
- "http"
paths:
  /html2pdf:
    post:
      tags:
      - "html2pdf"
      summary: "Convert html with addtional files to pdf"
      description: ""
      operationId: "html2pdf"
      consumes:
      - "application/json"
      produces:
      - "application/pdf"
      parameters:
      - in: "body"
        name: "body"
        description: "data for conversion"
        required: true
        schema:
          $ref: "#/definitions/body"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "controllers.html2pdf_controller"
definitions:
  html2pdf_extrafiles:
    required:
    - "content"
    - "name"
    properties:
      name:
        type: "string"
      content:
        type: "string"
        format: "binary"
  body:
    type: "object"
    required:
    - "basedocument"
    properties:
      basedocument:
        type: "string"
        format: "binary"
      extrafiles:
        type: "array"
        items:
          $ref: "#/definitions/html2pdf_extrafiles"
